project:
  type: website
  resources:
    - CNAME

website:
  title: "Elijah Pivo"
  site-url: "https://elijahpivo.com"
  favicon: images/favicon.png
  search: false
  google-analytics: "G-EB62W4D5LV"

  page-footer:
    center: "© 2026 Elijah Pivo · [Email](mailto:epivo@mit.edu) · [LinkedIn](https://www.linkedin.com/in/epivo/)"
    background: light

  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      # - about.qmd
    # right:
    #   - text: Email
    #     href: mailto:epivo@mit.edu

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    grid:
      body-width: 1800px



