project:
  type: website
  resources:
    - CNAME

website:
  title: "Elijah Pivo"
  site-url: "https://elijahpivo.com"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



